### ISSUE TITLE
Error: Switchboard account parser was not provided with an aggregator account: EsQkrtuJdRnDp6JvAcmRiYGoQbWL668TEZDW8VmrNcm3

### ISSUE THREAD

**Issue by CMEONE** [solendprotocol/liquidator#31]
When I run `docker-compose up --build`, I see a few failing transactions (`Liquidation is too small to receive collateral`) followed by a program crash with the following error log:

```
liquidator-main_1  | Obligation 2aTLzTGA8fjbAcvYeGvrPXNwTouCCh1F5GGjWqYmasgL is underwater
liquidator-main_1  |               borrowedValue: 2132231163805.25079802407945016631
liquidator-main_1  |               unhealthyBorrowValue: 2004509457679.6169569931682102497
liquidator-main_1  |               market address: 4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY
liquidator-main_1  | failed to get wallet balance for SOL to liquidate obligation 2aTLzTGA8fjbAcvYeGvrPXNwTouCCh1F5GGjWqYmasgL in market: 4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY. 
liquidator-main_1  |                 Potentially network error or token account does not exist in wallet
liquidator-main_1  | /home/solend/app/node_modules/@switchboard-xyz/switchboard-api/lib/switchboard_module.js:52
liquidator-main_1  |             throw new Error(`Switchboard account parser was not provided with an aggregator account: ${address.toBase58()}`);
liquidator-main_1  |                   ^
liquidator-main_1  | Error: Switchboard account parser was not provided with an aggregator account: EsQkrtuJdRnDp6JvAcmRiYGoQbWL668TEZDW8VmrNcm3
liquidator-main_1  |     at Object.<anonymous> (/home/solend/app/node_modules/@switchboard-xyz/switchboard-api/lib/switchboard_module.js:52:19)
liquidator-main_1  |     at Generator.next (<anonymous>)
liquidator-main_1  |     at fulfilled (/home/solend/app/node_modules/@switchboard-xyz/switchboard-api/lib/switchboard_module.js:5:58)
liquidator-main_1  |     at runMicrotasks (<anonymous>)
liquidator-main_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by 0xCactus** [comment]
@CMEONE Issue fixed in https://github.com/solendprotocol/liquidator/pull/30
